// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMlcxBV7EK9Uk_cufD-E8UF4vVAIMu-3Q',
    appId: '1:662225877096:web:8ed59bbb7a7d1b397d63dd',
    messagingSenderId: '662225877096',
    projectId: 'app1-82f72',
    authDomain: 'app1-82f72.firebaseapp.com',
    storageBucket: 'app1-82f72.appspot.com',
    measurementId: 'G-L6S70CR609',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7UtiIYyFZUKH3y8ORo_Uv4E0Qsjb6hM8',
    appId: '1:662225877096:android:7ae1145bba90fca57d63dd',
    messagingSenderId: '662225877096',
    projectId: 'app1-82f72',
    storageBucket: 'app1-82f72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwm0BcwOb2oiD3iqJR18c73ZwAcMkI-VM',
    appId: '1:662225877096:ios:6c5e4001574f18537d63dd',
    messagingSenderId: '662225877096',
    projectId: 'app1-82f72',
    storageBucket: 'app1-82f72.appspot.com',
    iosBundleId: 'com.example.harry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwm0BcwOb2oiD3iqJR18c73ZwAcMkI-VM',
    appId: '1:662225877096:ios:6c5e4001574f18537d63dd',
    messagingSenderId: '662225877096',
    projectId: 'app1-82f72',
    storageBucket: 'app1-82f72.appspot.com',
    iosBundleId: 'com.example.harry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMlcxBV7EK9Uk_cufD-E8UF4vVAIMu-3Q',
    appId: '1:662225877096:web:5afd8a3506ecfa7c7d63dd',
    messagingSenderId: '662225877096',
    projectId: 'app1-82f72',
    authDomain: 'app1-82f72.firebaseapp.com',
    storageBucket: 'app1-82f72.appspot.com',
    measurementId: 'G-MYDRWNECCL',
  );
}
